version: "3.4"
services:
  client:
    image: node:16-alpine
    ports:
      - "3000:3000"
    working_dir: /app/client
    volumes:
      - ../meetme:/app/client
    environment:
      NODE_ENV: development
      CHOKIDAR_USEPOLLING: "yes"
    command: sh -c "yarn install && yarn start"
